### ISSUE TITLE
config mask

### ISSUE THREAD

**Issue by txblue** [excaliburpartners/hassio-addons#1]
For some reason the mask (validation/format) check behind some of the config entries is giving me a problem. E.g. 7 char into usual IP4 address format then turns red. Interesting: 

It stays black (valid) with 
> "controller_address": 192.16811111111111111,

But this turns red at: 
> "controller_address": 192.168.

There are other fields that hiccup. Pops up in 3 different browsers. I did not dig into the code behind window to try to find where and why. 

On the other hand: THANK YOU for this. My MQTT server is on my desktop computer and as of yesterday it will not start - complains about MySQL issue now.

**Comment by rwagoner** [comment]
The field validation is set to string. Try putting it in quotes. For example
"controller_address": "192.168.1.100"

**Comment by txblue** [comment]
that makes sense. the port is not a string (number) but …. I thought I tried putting "the strings" in quotes, I did but too impatient to wait for final comma to completely validate input. 
Thanks! 
And away we go:

> OmniLinkBridge.Modules.LoggerModule: 2019-12-26 13:51:45,335 DEBUG: ThermostatStatus 1 MBR tstat1, Status: 68 OFF, Heat: 66, Cool: 70, Mode: COOL, Fan: AUTO, Hold: ON
