### ISSUE TITLE
OLB control Thermostat Hold status

### ISSUE THREAD

**Issue by ifuchs** [excaliburpartners/hassio-addons#3]
Is there a way to turn off Hold if it is set on thermostat? I can control temperatures and modes but I don't see a way to turn off Hold. When I leave the house for an extended period, I often turn on Hold at the thermostat. It would nice if there were a way to turn it off remotely.

**Comment by rwagoner** [comment]
It is possible to turn off hold using MQTT by publishing off to omnilink/thermostat1/hold_command. I haven't been able to get it to work with the Home Assistant MQTT Climate integration. Home Assistant will show you if hold is on, but doesn't provide the option to change it.

**Comment by ifuchs** [comment]
If I can do it "manually" using MQTT, could you tell exactly how that is done (I have not played with MQTT other than by using it with the OLB integration)?

**Comment by rwagoner** [comment]
Closing this as the hold can now be changed using the climate preset option.
