### ISSUE TITLE
Fix MQTT alarm control panel for Home Assistant 2024.6

### ISSUE THREAD

**Issue by peteeee** [excaliburpartners/hassio-addons#5]
1.1.19.1
Fix MQTT alarm control panel for Home Assistant 2024.6

Lost alarm control panel with update.

![FireShot Capture 260 - Overview – Home Assistant - 192 168 244 174](https://github.com/excaliburpartners/hassio-addons/assets/8072890/5a1da748-d62b-418c-8981-984af37d5499)

**Comment by rwagoner** [comment]
Please ensure you are running Home Assistant 2024.6. The previous version of OmniLink Bridge had an error arming on 2024.6 "Validation error: Arming requires a code but none was given for alarm_control_panel.area_1". OmniLike Bridge now sets these additional fields, which appears to break it on previous Home Assistant versions.

**Comment by peteeee** [comment]
Thank you Ryan.  Yes running 2024.6.1

Keyboard showed fine with Core 2024.6

Home Assistant
Core 2024.6.1
Supervisor 2024.06.0
Operating System 12.3
Frontend 20240605.0

**Comment by peteeee** [comment]
Hello Ryan,
Downgraded to V18 on HA and see keypad.  That said keypad doesn't arm or disarm panel.  It does show status of arming if I use hardware keypad to arm.

![OmniLinkBridgeV18-1](https://github.com/excaliburpartners/hassio-addons/assets/8072890/e8d5310a-74d8-46fe-a74a-c68967dc7327)


![OmniLinkBridgeV18](https://github.com/excaliburpartners/hassio-addons/assets/8072890/43c14fb3-184e-4fc8-bdaf-ca993b2c6377)

**Comment by rwagoner** [comment]
With Home Assistant 2024.6 and OmniLink Bridge 1.1.18 and prior, in Home Assistant the workaround I've heard is to edit the alarm control panel entity settings and set the default code field.

What issue were you encountering with OmniLink Bridge 1.1.19 and Home Assistant 2024.6? You mentioned you lost the alarm control panel, but I'm not entirely sure what that means.

**Comment by peteeee** [comment]
Hello Ryan.  I lost the keypad under "OmniPro Alarm".

Note the alarm keypad is present with OmniBridge 1.1.18 and not present with the OmniBridge 1.1.19 versions in the above images.

**Comment by rwagoner** [comment]
Ah I see now. I'm guessing you had `mqtt_discovery_area_code_required: 1` set previously. With 1.1.19 I changed the config to `mqtt_discovery_override_area` to support additional options. I usually don't make breaking config changes, but did this time as the alarm control panel was broken anyway with the Home Assistant release. To get the previous behavior for OmniPro area 1 you would set the following:

`mqtt_discovery_override_area: id=1;code_arm=true;code_disarm=true;`

**Comment by peteeee** [comment]
Thank you Ryan.  

I set the following as stated:

mqtt_discovery_override_area: id=1;code_arm=true;code_disarm=true;

and now see the keypad.
